### ISSUE TITLE
google.cloud.language.v1 not appearing in index

### ISSUE THREAD

**Issue by danoscarmike** [googleapis/googleapis-api-index-generator#7]
cc/ @dwsupplee

**Comment by jskeet** [comment]
The service config YAML file isn't in the same directory as the service (https://github.com/googleapis/googleapis/tree/master/google/cloud/language/v1). There's a YAML file in the parent directory, but we moved to putting them in the same directory as the service ages ago.

It's *possible* that we can just move the file, but there may be other things we need to do at the same time.

Dan, can you liaise with the tools team to go through their normal process for this?

**Comment by danoscarmike** [comment]
Fixing internally.

**Comment by jskeet** [comment]
Looks like this is now done, given https://github.com/googleapis/googleapis/commit/84357f423fee6a61bafbcf390d42d4fe6afd9cf8
